{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE TemplateHaskellQuotes #-}

{- | Singleton keys: the name vocabulary of chart specifications.

Every name a chart mentions — states, events, guards, actions, services,
invoke ids, done-data outputs — is a /promoted constructor/ of an ordinary
Haskell sum type, one type per role:

@
data TrafficState = Green | Yellow | Red
data TrafficEvent = TIMER | POWER_OUT

'deriveKeyKind' ''TrafficState
'deriveKeyKind' ''TrafficEvent
@

'deriveKeyKind' equips the type to be used as a /kind/ whose constructors
are chart keys: a singleton @'SKey' x@ per constructor (@SGreen ::
SKey \'Green@, …), 'Data.Type.Equality.TestEquality' over those singletons,
and the 'KeyKind' dictionary connecting the three representations of a key:

* the /type-level/ key @\'Green@ (what charts are written with),
* the /singleton/ @SGreen :: SKey \'Green@ (runtime evidence for a
  type-level key), and
* the /value/ @Green :: TrafficState@ (what runtime queries return).

Reify with 'demote' \/ 'demoteKey' (type → value), go back up with
'promoteKey' \/ 'withKey' (value → type, existentially), and cross the
serialization boundary with 'keyName' \/ 'parseKey' (value ↔ 'Text' — this
is the name that appears in snapshots, traces, and rendered charts).

Roles a chart does not use are pinned to the uninhabited 'NoKey'.
-}
module StateMachine.Key (
  -- * Singletons
  SKey,
  KnownKey (..),

  -- * Key kinds
  KeyKind (..),
  parseKey,

  -- * Existentials
  SomeKey (..),
  withSomeKey,
  withKey,
  someKeyName,

  -- * Reify \/ demote sugar
  demote,
  keyNameOf,

  -- * Unused roles
  NoKey,

  -- * Deriving
  deriveKeyKind,
  deriveKeyKindWith,
) where

import Data.Kind (Constraint, Type)
import Data.List (find)
import Data.Text (Text)
import Data.Text qualified as T
import Data.Type.Equality (TestEquality (..), (:~:) (..))
import Language.Haskell.TH qualified as TH

{-------------------------------------------------------------------------------
  Singletons
-------------------------------------------------------------------------------}

-- | The singleton family: @SKey (x :: k)@ has exactly one inhabitant per
-- promoted constructor @x@ of the key kind @k@. Instances are generated by
-- 'deriveKeyKind'.
data family SKey :: k -> Type

-- | A type-level key whose singleton is known. Every promoted constructor
-- of a derived key kind satisfies this. (The kind is an /inferred/
-- parameter, so @skey \@\'Green@ works without spelling it.)
type KnownKey :: forall {k}. k -> Constraint
class (KeyKind k) => KnownKey (x :: k) where
  -- | The singleton for a type-level key: @skey \@\'Green :: SKey \'Green@.
  skey :: SKey x

{-------------------------------------------------------------------------------
  Key kinds
-------------------------------------------------------------------------------}

{- | A kind whose promoted constructors are chart keys. Instances are
generated by 'deriveKeyKind'; the type must be a plain enumeration (no
type parameters, all constructors nullary).

Laws (the derived instances satisfy them by construction):

* @'promoteKey' ('demoteKey' s) = 'SomeKey' s@
* @'keyName'@ is injective on the constructors
* @'keyUniverse'@ lists every constructor exactly once, in declaration
  order
-}
class (TestEquality (SKey :: k -> Type)) => KeyKind k where
  -- | Reify a singleton to its ordinary value: @demoteKey SGreen = Green@.
  demoteKey :: SKey (x :: k) -> k

  -- | Promote a value to its (existentially wrapped) singleton:
  -- @promoteKey Green = SomeKey SGreen@.
  promoteKey :: k -> SomeKey k

  -- | The wire\/display name of a key — what snapshots, traces, and
  -- rendered charts show. Derived as the constructor name (or the rename
  -- given to 'deriveKeyKindWith').
  keyName :: k -> Text

  -- | Every key of the kind, in declaration order.
  keyUniverse :: [SomeKey k]

-- | Parse a wire name back to a key: the inverse of 'keyName'.
parseKey :: forall k. (KeyKind k) => Text -> Maybe (SomeKey k)
parseKey t = find ((t ==) . someKeyName) (keyUniverse @k)

{-------------------------------------------------------------------------------
  Existentials
-------------------------------------------------------------------------------}

-- | A singleton for a key of kind @k@ that is not statically known —
-- what 'promoteKey' and 'parseKey' return.
data SomeKey k where
  SomeKey :: (KnownKey (x :: k)) => SKey x -> SomeKey k

instance (KeyKind k) => Eq (SomeKey k) where
  SomeKey a == SomeKey b = case testEquality a b of
    Just Refl -> True
    Nothing -> False

instance (KeyKind k) => Show (SomeKey k) where
  showsPrec d k =
    showParen (d > 10) $
      showString "SomeKey " . showsPrec 11 (someKeyName k)

-- | Eliminate a 'SomeKey' with the key back at the type level.
withSomeKey :: SomeKey k -> (forall (x :: k). (KnownKey x) => SKey x -> r) -> r
withSomeKey (SomeKey s) f = f s

-- | Promote a value straight into a continuation:
-- @withKey Green (\\s -> …)@ runs with @s :: SKey \'Green@.
withKey :: (KeyKind k) => k -> (forall (x :: k). (KnownKey x) => SKey x -> r) -> r
withKey v = withSomeKey (promoteKey v)

-- | The wire name of an existentially wrapped key.
someKeyName :: (KeyKind k) => SomeKey k -> Text
someKeyName (SomeKey s) = keyName (demoteKey s)

{-------------------------------------------------------------------------------
  Reify / demote sugar
-------------------------------------------------------------------------------}

-- | Reify a type-level key to its value: @demote \@\'Green = Green@.
demote :: forall {k} (x :: k). (KnownKey x) => k
demote = demoteKey (skey @x)

-- | The wire name of a type-level key: @keyNameOf \@\'Green = \"Green\"@.
keyNameOf :: forall {k} (x :: k). (KnownKey x) => Text
keyNameOf = keyName (demote @x)

{-------------------------------------------------------------------------------
  Unused roles
-------------------------------------------------------------------------------}

-- | The empty key kind: pin a chart's unused roles to it (no guards, no
-- services, …). Uninhabited, so a chart with @NoKey@ guards provably
-- mentions none, and the guard registry is exactly 'StateMachine.Registry.RNil'.
data NoKey

data instance SKey (x :: NoKey)

instance TestEquality (SKey :: NoKey -> Type) where
  testEquality x _ = case x of {}

instance KeyKind NoKey where
  demoteKey x = case x of {}
  promoteKey v = case v of {}
  keyName v = case v of {}
  keyUniverse = []

{-------------------------------------------------------------------------------
  Deriving
-------------------------------------------------------------------------------}

{- | Derive the key-kind instances for a plain enumeration:

@
data TrafficState = Green | Yellow | Red
deriveKeyKind ''TrafficState
@

generates the singletons (@SGreen :: SKey \'Green@, …, one @S@-prefixed
constructor per constructor), @TestEquality (SKey :: TrafficState ->
Type)@, @'KeyKind' TrafficState@ (with 'keyName' the constructor name),
and a @'KnownKey'@ instance per constructor.
-}
deriveKeyKind :: TH.Name -> TH.Q [TH.Dec]
deriveKeyKind = deriveKeyKindWith id

-- | 'deriveKeyKind' with a rename applied to constructor names to obtain
-- 'keyName' (e.g. @deriveKeyKindWith (map toLower)@ for XState-style
-- lowercase state names). The rename must stay injective on the
-- constructors and may not produce @\"#root\"@ (reserved for the
-- synthetic root).
deriveKeyKindWith :: (String -> String) -> TH.Name -> TH.Q [TH.Dec]
deriveKeyKindWith rename tyName = do
  info <- TH.reify tyName
  ctors <- case info of
    TH.TyConI (TH.DataD _ _ tvs _ cons _)
      | not (null tvs) ->
          fail (prefix <> "the type must not have type parameters")
      | otherwise -> traverse nullaryCtor cons
    _ -> fail (prefix <> "expected a plain data declaration")
  case ctors of
    [] -> fail (prefix <> "the type must have at least one constructor (use NoKey for unused roles)")
    _ -> pure ()
  let names = map (rename . TH.nameBase) ctors
  checkNames names
  let singNames = map (TH.mkName . ("S" <>) . TH.nameBase) ctors
      keys = zipWith3 Key ctors singNames names
      catchAll = case keys of
        _ : _ : _ -> [TH.Clause [TH.WildP, TH.WildP] (TH.NormalB (TH.ConE 'Nothing)) []]
        _ -> []
      singletonDecl x =
        TH.DataInstD
          []
          (Just [TH.KindedTV x () (TH.ConT tyName)])
          (TH.ConT ''SKey `TH.AppT` TH.SigT (TH.VarT x) (TH.ConT tyName))
          Nothing
          (map gadtCtor keys)
          []
      gadtCtor k =
        TH.GadtC [kSing k] [] (TH.ConT ''SKey `TH.AppT` TH.PromotedT (kCtor k))
      testEqualityDecl =
        TH.InstanceD
          Nothing
          []
          (TH.ConT ''TestEquality `TH.AppT` skeyAtKind)
          [TH.FunD 'testEquality (map reflClause keys <> catchAll)]
      reflClause k =
        TH.Clause
          [TH.ConP (kSing k) [] [], TH.ConP (kSing k) [] []]
          (TH.NormalB (TH.ConE 'Just `TH.AppE` TH.ConE 'Refl))
          []
      keyKindDecl =
        TH.InstanceD
          Nothing
          []
          (TH.ConT ''KeyKind `TH.AppT` TH.ConT tyName)
          [ TH.FunD 'demoteKey (map demoteClause keys)
          , TH.FunD 'promoteKey (map promoteClause keys)
          , TH.FunD 'keyName (map nameClause keys)
          , TH.FunD
              'keyUniverse
              [TH.Clause [] (TH.NormalB (TH.ListE (map someKeyE keys))) []]
          ]
      demoteClause k =
        TH.Clause [TH.ConP (kSing k) [] []] (TH.NormalB (TH.ConE (kCtor k))) []
      promoteClause k =
        TH.Clause [TH.ConP (kCtor k) [] []] (TH.NormalB (someKeyE k)) []
      nameClause k =
        TH.Clause [TH.ConP (kCtor k) [] []] (TH.NormalB (textE (kName k))) []
      someKeyE k = TH.ConE 'SomeKey `TH.AppE` TH.ConE (kSing k)
      knownKeyDecl k =
        TH.InstanceD
          Nothing
          []
          (TH.ConT ''KnownKey `TH.AppT` TH.SigT (TH.PromotedT (kCtor k)) (TH.ConT tyName))
          [TH.FunD 'skey [TH.Clause [] (TH.NormalB (TH.ConE (kSing k))) []]]
  x <- TH.newName "x"
  pure ([singletonDecl x, testEqualityDecl, keyKindDecl] <> map knownKeyDecl keys)
 where
  prefix = "deriveKeyKind " <> show tyName <> ": "

  skeyAtKind =
    TH.SigT
      (TH.ConT ''SKey)
      (TH.ArrowT `TH.AppT` TH.ConT tyName `TH.AppT` TH.StarT)

  nullaryCtor = \case
    TH.NormalC n [] -> pure n
    TH.NormalC n _ ->
      fail (prefix <> "constructor " <> TH.nameBase n <> " has fields; keys must be nullary")
    c -> fail (prefix <> "unsupported constructor shape: " <> show c)

  checkNames names = do
    case filter (\n -> length (filter (== n) names) > 1) names of
      dup : _ -> fail (prefix <> "rename produces duplicate key name " <> show dup)
      [] -> pure ()
    case find (== "#root") names of
      Just _ -> fail (prefix <> "key name \"#root\" is reserved for the synthetic root")
      Nothing -> pure ()

  textE s = TH.VarE 'T.pack `TH.AppE` TH.LitE (TH.StringL s)

-- | One constructor of a key kind during derivation: the original
-- constructor, its generated singleton constructor, and its wire name.
data Key = Key
  { kCtor :: TH.Name
  , kSing :: TH.Name
  , kName :: String
  }
