{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.FieldMask where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x20\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x66\x69\x65\x6c\x64\x5f\x6d\x61\x73\x6b\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x1a\x0a\x09\x46\x69\x65\x6c\x64\x4d\x61\x73\x6b\x12\x0d\x0a\x05\x70\x61\x74\x68\x73\x18\x01\x20\x03\x28\x09\x62\x06\x70\x72\x6f\x74\x6f\x33"


data FieldMask = FieldMask
  { fieldMaskPaths :: !(V.Vector Text)
  , fieldMaskUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultFieldMask :: FieldMask
defaultFieldMask = FieldMask
  { fieldMaskPaths = V.empty
  , fieldMaskUnknownFields = []
  }

instance MessageEncode FieldMask where
  buildMessage msg =
    V.foldl' (\acc v -> acc <> archString 10 v) mempty msg.fieldMaskPaths
    <> encodeUnknownFields msg.fieldMaskUnknownFields

instance MessageSize FieldMask where
  messageSize msg =
    (V.foldl' (\acc v -> acc + archStringSize v) 0 msg.fieldMaskPaths)
    + unknownFieldsSize msg.fieldMaskUnknownFields

instance MessageDecode FieldMask where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop V.empty []
    where
      loop acc_0 acc_unknown_ = do
        mTag <- getTagOrU
        case mTag of
          UNothing -> pure (FieldMask {fieldMaskPaths = acc_0, fieldMaskUnknownFields = reverse acc_unknown_})
          UJust (Tag fn wt) -> case fn of
            1 -> do
              v <- decodeFieldString
              loop (acc_0 <> V.singleton v) acc_unknown_
            _ -> do
              uf <- captureUnknownField fn wt
              loop acc_0 (uf : acc_unknown_)

instance IsMessage FieldMask where
  messageTypeName _ = "google.protobuf.FieldMask"

instance ProtoMessage FieldMask where
  protoMessageName _ = "google.protobuf.FieldMask"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultFieldMask
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "paths"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelRepeated
        , fdGet = fieldMaskPaths
        , fdSet = \v m -> m { fieldMaskPaths = v }
        })
    ]

-- proto3 JSON: google.protobuf.FieldMask serialises as a comma-separated
-- string of dotted lower_with_underscores → lowerCamelCase paths.
-- Empty FieldMask -> empty string.
instance Aeson.ToJSON FieldMask where
  toJSON msg =
    Aeson.String $
      T.intercalate (T.pack ",")
        (V.toList (V.map snakeToCamelPath msg.fieldMaskPaths))

instance Aeson.FromJSON FieldMask where
  parseJSON = Aeson.withText "FieldMask" $ \t -> do
    let parts = if T.null t then [] else T.splitOn (T.pack ",") t
    pure defaultFieldMask
      { fieldMaskPaths = V.fromList (fmap camelToSnakePath parts)
      }

-- | Convert each segment of a dotted FieldMask path from
-- @lower_with_underscores@ to @lowerCamelCase@.
snakeToCamelPath :: Text -> Text
snakeToCamelPath = T.intercalate (T.pack ".") . fmap snakeToCamel . T.splitOn (T.pack ".")
  where
    snakeToCamel :: Text -> Text
    snakeToCamel s =
      let parts = T.splitOn (T.pack "_") s
      in case parts of
           []     -> T.empty
           (h:rs) -> h <> T.concat (fmap upperFirst rs)
    upperFirst t = case T.uncons t of
      Just (c, rest) -> T.cons (toUpperC c) rest
      Nothing        -> t
    toUpperC c
      | c >= 'a' && c <= 'z' = toEnum (fromEnum c - 32)
      | otherwise = c

-- | Inverse of 'snakeToCamelPath' for parse-side. Per spec the parser
-- MUST reject ill-formed FieldMasks; we accept canonical lowerCamelCase
-- and translate it back to lower_with_underscores.
camelToSnakePath :: Text -> Text
camelToSnakePath = T.intercalate (T.pack ".") . fmap camelToSnake . T.splitOn (T.pack ".")
  where
    camelToSnake :: Text -> Text
    camelToSnake = T.concatMap (\c ->
      if c >= 'A' && c <= 'Z'
        then T.pack ['_', toLowerC c]
        else T.singleton c)
    toLowerC c
      | c >= 'A' && c <= 'Z' = toEnum (fromEnum c + 32)
      | otherwise = c

instance Hashable FieldMask where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.fieldMaskPaths

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy FieldMask) .  id