{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.Timestamp where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe)
import Data.Proxy (Proxy(..))
import Proto.Message (IsMessage(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import qualified Proto.Registry
import Proto.Wire (Tag(..), WireType(..))
import Proto.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x1f\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x2b\x0a\x09\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x12\x0f\x0a\x07\x73\x65\x63\x6f\x6e\x64\x73\x18\x01\x20\x01\x28\x03\x12\x0d\x0a\x05\x6e\x61\x6e\x6f\x73\x18\x02\x20\x01\x28\x05\x62\x06\x70\x72\x6f\x74\x6f\x33"


data Timestamp = Timestamp
  { timestampSeconds :: {-# UNPACK #-} !Int64
  , timestampNanos :: {-# UNPACK #-} !Int32
  , timestampUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultTimestamp :: Timestamp
defaultTimestamp = Timestamp
  { timestampSeconds = 0
  , timestampNanos = 0
  , timestampUnknownFields = []
  }

instance MessageEncode Timestamp where
  buildMessage msg =
    (if msg.timestampSeconds == 0 then mempty else archVarint 8 (fromIntegral msg.timestampSeconds))
    <> (if msg.timestampNanos == 0 then mempty else archVarint 16 (fromIntegral msg.timestampNanos))
    <> encodeUnknownFields msg.timestampUnknownFields

instance MessageSize Timestamp where
  messageSize msg =
    (if msg.timestampSeconds == 0 then 0 else archVarintSize (fromIntegral msg.timestampSeconds))
    + (if msg.timestampNanos == 0 then 0 else archVarintSize (fromIntegral msg.timestampNanos))
    + unknownFieldsSize msg.timestampUnknownFields

instance MessageDecode Timestamp where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop_dispatch 0 0 []
    where
      loop_dispatch acc_0 acc_1 acc_unknown_ = withTagM
        (pure (Timestamp {timestampSeconds = acc_0, timestampNanos = acc_1, timestampUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop_after_0 v acc_1 acc_unknown_
          2 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop_after_1 acc_0 v acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop_dispatch acc_0 acc_1 (uf : acc_unknown_))
      loop_after_0 acc_0 acc_1 acc_unknown_ = withTagM
        (pure (Timestamp {timestampSeconds = acc_0, timestampNanos = acc_1, timestampUnknownFields = reverse acc_unknown_}))
        (\fn wt -> if fn == 2
          then do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop_after_1 acc_0 v acc_unknown_
          else case fn of
            1 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop_after_0 v acc_1 acc_unknown_
            _ -> do
              uf <- captureUnknownField fn (toEnum wt)
              loop_dispatch acc_0 acc_1 (uf : acc_unknown_))
      loop_after_1 acc_0 acc_1 acc_unknown_ = withTagM
        (pure (Timestamp {timestampSeconds = acc_0, timestampNanos = acc_1, timestampUnknownFields = reverse acc_unknown_}))
        (\fn wt -> if fn == 1
          then do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop_after_0 v acc_1 acc_unknown_
          else case fn of
            2 -> do
              v <- (fromIntegral <$> decodeFieldVarint)
              loop_after_1 acc_0 v acc_unknown_
            _ -> do
              uf <- captureUnknownField fn (toEnum wt)
              loop_dispatch acc_0 acc_1 (uf : acc_unknown_))

instance IsMessage Timestamp where
  messageTypeName _ = "google.protobuf.Timestamp"

instance ProtoMessage Timestamp where
  protoMessageName _ = "google.protobuf.Timestamp"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultTimestamp
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "seconds"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int64Field
        , fdLabel = LabelOptional
        , fdGet = timestampSeconds
        , fdSet = \v m -> m { timestampSeconds = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "nanos"
        , fdNumber = 2
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = timestampNanos
        , fdSet = \v m -> m { timestampNanos = v }
        })
    ]

instance Aeson.ToJSON Timestamp where
  toJSON msg =
    let s = msg.timestampSeconds
        n = msg.timestampNanos
        (rawDays, remSec) = s `divMod` 86400
        (hours, remH) = remSec `divMod` 3600
        (mins, secs) = remH `divMod` 60
        z = rawDays + 719468
        era = (if z >= 0 then z else z - 146096) `div` 146097
        doe = z - era * 146097
        yoe = (doe - doe `div` 1460 + doe `div` 36524 - doe `div` 146096) `div` 365
        y = yoe + era * 400
        doy = doe - (365 * yoe + yoe `div` 4 - yoe `div` 100)
        mp = (5 * doy + 2) `div` 153
        d = doy - (153 * mp + 2) `div` 5 + 1
        m = mp + (if mp < 10 then 3 else -9)
        y' = y + (if m <= 2 then 1 else 0)
        pad2 x = let sx = T.pack (show (abs x)) in if T.length sx < 2 then T.pack "0" <> sx else sx
        pad4 x = let sx = T.pack (show (abs x)) in T.replicate (4 - T.length sx) (T.pack "0") <> sx
        pad9 x = let sx = T.pack (show (abs x)) in T.replicate (9 - T.length sx) (T.pack "0") <> sx
        nanoStr = if n == 0 then T.pack "" else T.pack "." <> dropTrailingZeros (pad9 (fromIntegral n))
        dropTrailingZeros t = case T.stripSuffix (T.pack "0") t of { Just t' -> dropTrailingZeros t'; Nothing -> t }
    in Aeson.String (pad4 y' <> T.pack "-" <> pad2 (fromIntegral m) <> T.pack "-" <> pad2 (fromIntegral d)
         <> T.pack "T" <> pad2 hours <> T.pack ":" <> pad2 mins <> T.pack ":" <> pad2 secs
         <> nanoStr <> T.pack "Z")


instance Aeson.FromJSON Timestamp where
  parseJSON (Aeson.String t) = case parseRfc3339Inline t of
    Right ts -> pure ts
    Left  e  -> fail e
  parseJSON _ = fail "Expected RFC 3339 timestamp string"

-- | Parse an RFC 3339 timestamp into seconds + nanos. Spelled out here
-- (rather than calling out to "Proto.JSON.WellKnown") because that
-- module imports this one.
parseRfc3339Inline :: T.Text -> Either String Timestamp
parseRfc3339Inline raw =
  let stripped = T.strip raw
  in case T.breakOn (T.pack "T") stripped of
       (datePart, rest)
         | T.null rest -> Left "Invalid RFC 3339 timestamp: missing T separator"
         | otherwise   ->
             let timePart' = T.drop 1 rest
                 (timePart, !offsetSecs) = stripOffset timePart'
             in case (parseDate datePart, parseTime timePart) of
                  (Right (yr, mo, dy), Right (hr, mn, se, ns)) ->
                    let !days     = daysFromCivilT yr mo dy - 719468
                        !rawSecs  = fromIntegral days * 86400
                                  + fromIntegral hr * 3600
                                  + fromIntegral mn * 60
                                  + fromIntegral se
                        !utcSecs  = rawSecs - fromIntegral offsetSecs
                    in Right defaultTimestamp
                         { timestampSeconds = utcSecs
                         , timestampNanos   = ns
                         }
                  (Left e, _) -> Left e
                  (_, Left e) -> Left e
  where
    stripOffset :: T.Text -> (T.Text, Int)
    stripOffset s
      | T.null s = (s, 0)
      | T.last s == 'Z' || T.last s == 'z' = (T.init s, 0)
      | otherwise = case findTzStart s of
          Nothing      -> (s, 0)
          Just (i, sg) ->
            let (tt, tz) = T.splitAt i s
                tzBody   = T.tail tz
                noColon  = T.replace (T.pack ":") (T.pack "") tzBody
                hh       = readIntDef (T.take 2 noColon)
                mm       = readIntDef (T.take 2 (T.drop 2 noColon))
                !off     = sg * (hh * 3600 + mm * 60)
            in (tt, off)

    findTzStart :: T.Text -> Maybe (Int, Int)
    findTzStart = goLast Nothing 0 . T.unpack
      where
        goLast best _ []     = best
        goLast best i (c:cs)
          | c == '+'          = goLast (Just (i,  1)) (i+1) cs
          | c == '-' && i > 0 = goLast (Just (i, -1)) (i+1) cs
          | otherwise         = goLast best (i+1) cs

    parseDate :: T.Text -> Either String (Int, Int, Int)
    parseDate t = case T.splitOn (T.pack "-") t of
      [ys, ms, ds] -> do
        y <- readEither ys
        m <- readEither ms
        d <- readEither ds
        Right (y, m, d)
      _ -> Left "Invalid date format"

    parseTime :: T.Text -> Either String (Int, Int, Int, Int32)
    parseTime t =
      let (wholePart, fracPart) = T.breakOn (T.pack ".") t
      in case T.splitOn (T.pack ":") wholePart of
           [hs, ms, ss] -> do
             h  <- readEither hs
             mn <- readEither ms
             s  <- readEither ss
             Right (h, mn, s, parseFracNanos fracPart)
           _ -> Left "Invalid time format"

    parseFracNanos :: T.Text -> Int32
    parseFracNanos t
      | T.null t = 0
      | T.head t == '.' =
          let digits = T.takeWhile (\c -> c >= '0' && c <= '9') (T.tail t)
              padded = T.take 9 (digits <> T.replicate (9 - T.length digits) (T.pack "0"))
          in case readEither padded of
               Right n -> fromIntegral (n :: Int)
               Left _  -> 0
      | otherwise = 0

    readEither :: T.Text -> Either String Int
    readEither t = case reads (T.unpack t) of
      [(n, "")] -> Right n
      _         -> Left ("Bad integer: " <> T.unpack t)

    readIntDef :: T.Text -> Int
    readIntDef t = either (const 0) id (readEither t)

    daysFromCivilT :: Int -> Int -> Int -> Int
    daysFromCivilT y m d =
      let !y'  = y - (if m <= 2 then 1 else 0)
          !era = (if y' >= 0 then y' else y' - 399) `quot` 400
          !yoe = y' - era * 400
          !doy = (153 * (m + (if m > 2 then -3 else 9)) + 2) `quot` 5 + d - 1
          !doe = yoe * 365 + yoe `quot` 4 - yoe `quot` 100 + doy
      in era * 146097 + doe


instance Hashable Timestamp where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.timestampSeconds) msg.timestampNanos

-- | Register all message types defined in this module.
registerModuleTypes :: Proto.Registry.MessageRegistry -> Proto.Registry.MessageRegistry
registerModuleTypes =
  Proto.Registry.registerType (Proxy :: Proxy Timestamp) .  id