{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.WellKnownTypes.Duration where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word8, Word32, Word64)
import qualified Data.IntMap.Strict as IntMap
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Internal.Encode
import Proto.Internal.Decode
import Proto.Internal.GrowList (GrowList, emptyGrowList, snocGrowList, growListToVector)
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON, OneofVariantNullSemantics (..), parseOneofVariants)
import Data.Proxy (Proxy(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Decode.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x1e\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x64\x75\x72\x61\x74\x69\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x2a\x0a\x08\x44\x75\x72\x61\x74\x69\x6f\x6e\x12\x0f\x0a\x07\x73\x65\x63\x6f\x6e\x64\x73\x18\x01\x20\x01\x28\x03\x12\x0d\x0a\x05\x6e\x61\x6e\x6f\x73\x18\x02\x20\x01\x28\x05\x62\x06\x70\x72\x6f\x74\x6f\x33"


data Duration = Duration
  { durationSeconds :: {-# UNPACK #-} !Int64
  , durationNanos :: {-# UNPACK #-} !Int32
  , durationUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultDuration :: Duration
defaultDuration = Duration
  { durationSeconds = 0
  , durationNanos = 0
  , durationUnknownFields = []
  }

instance MessageEncode Duration where
  buildSized msg =
    (if msg.durationSeconds == 0 then mempty else archVarint 8 (fromIntegral msg.durationSeconds))
    <> (if msg.durationNanos == 0 then mempty else archVarint 16 (fromIntegral msg.durationNanos))
    <> encodeUnknownFieldsSized msg.durationUnknownFields

instance MessageDecode Duration where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultDuration
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          (fromIntegral <$> decodeFieldVarint)
          (\v -> stage_1 (msg { durationSeconds = v}))
          (pure (case msg.durationUnknownFields of { [] -> msg; _ -> msg { durationUnknownFields = reverse (msg.durationUnknownFields) } }))
          (loop msg)
      stage_1 msg =
        inOrderStage1
          (0x10 :: Data.Word.Word8)
          (fromIntegral <$> decodeFieldVarint)
          (\v -> loop (msg { durationNanos = v}))
          (pure (case msg.durationUnknownFields of { [] -> msg; _ -> msg { durationUnknownFields = reverse (msg.durationUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.durationUnknownFields of { [] -> msg; _ -> msg { durationUnknownFields = reverse (msg.durationUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (msg { durationSeconds = v})
          2 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (msg { durationNanos = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { durationUnknownFields = (uf : msg.durationUnknownFields)}))

-- | Field descriptors for 'Duration', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
durationFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor Duration)
durationFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "seconds"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int64Field
        , fdLabel = LabelOptional
        , fdGet = durationSeconds
        , fdSet = \v m -> m { durationSeconds = v }
        }), (2, SomeField FieldDescriptor
        { fdName = "nanos"
        , fdNumber = 2
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = durationNanos
        , fdSet = \v m -> m { durationNanos = v }
        })
    ]

instance ProtoMessage Duration where
  protoMessageName _ = "google.protobuf.Duration"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultDuration
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = durationFieldDescriptors

instance IsMessage Duration

instance Aeson.ToJSON Duration where
  toJSON msg =
    let s = msg.durationSeconds
        n = msg.durationNanos
        nanoStr = if n == 0 then T.pack "" else T.pack "." <> dropTrailingZeros (pad9 (abs (fromIntegral n)))
        dropTrailingZeros t = case T.stripSuffix (T.pack "0") t of { Just t' -> dropTrailingZeros t'; Nothing -> t }
        pad9 x = let sx = T.pack (show x) in T.replicate (9 - T.length sx) (T.pack "0") <> sx
        sign = if s < 0 || n < 0 then T.pack "-" else T.pack ""
    in Aeson.String (sign <> T.pack (show (abs s)) <> nanoStr <> T.pack "s")


instance Aeson.FromJSON Duration where
  parseJSON (Aeson.String _) = pure defaultDuration
  parseJSON _ = fail "Expected duration string like \"3.5s\""


instance Hashable Duration where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.durationSeconds) msg.durationNanos

instance Proto.Extension.HasExtensions Duration where
  messageUnknownFields = durationUnknownFields
  setMessageUnknownFields !ufs msg = msg { durationUnknownFields = ufs }

instance Semigroup Duration where
  a <> b = Duration
    { durationSeconds = if b.durationSeconds == 0 then a.durationSeconds else b.durationSeconds
    , durationNanos = if b.durationNanos == 0 then a.durationNanos else b.durationNanos
    , durationUnknownFields = a.durationUnknownFields <> b.durationUnknownFields
    }

instance Monoid Duration where
  mempty = defaultDuration