{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.WellKnownTypes.FieldMask where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word8, Word32, Word64)
import qualified Data.IntMap.Strict as IntMap
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Internal.Encode
import Proto.Internal.Decode
import Proto.Internal.GrowList (GrowList, emptyGrowList, snocGrowList, growListToVector)
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON, OneofVariantNullSemantics (..), parseOneofVariants)
import Data.Proxy (Proxy(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Decode.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x20\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x66\x69\x65\x6c\x64\x5f\x6d\x61\x73\x6b\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x1a\x0a\x09\x46\x69\x65\x6c\x64\x4d\x61\x73\x6b\x12\x0d\x0a\x05\x70\x61\x74\x68\x73\x18\x01\x20\x03\x28\x09\x62\x06\x70\x72\x6f\x74\x6f\x33"


data FieldMask = FieldMask
  { fieldMaskPaths :: !(V.Vector Text)
  , fieldMaskUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultFieldMask :: FieldMask
defaultFieldMask = FieldMask
  { fieldMaskPaths = V.empty
  , fieldMaskUnknownFields = []
  }

instance MessageEncode FieldMask where
  buildSized msg =
    V.foldl' (\acc v -> acc <> archString 10 v) mempty msg.fieldMaskPaths
    <> encodeUnknownFieldsSized msg.fieldMaskUnknownFields

instance MessageDecode FieldMask where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultFieldMask emptyGrowList
    where
      stage_0 msg gl_0 =
        inOrderStage1
          (0xa :: Data.Word.Word8)
          decodeFieldString
          (\v -> stage_0 msg (snocGrowList gl_0 v))
          (pure (case msg.fieldMaskUnknownFields of { [] -> msg { fieldMaskPaths = growListToVector gl_0 }; _ -> msg { fieldMaskPaths = growListToVector gl_0, fieldMaskUnknownFields = reverse (msg.fieldMaskUnknownFields) } }))
          (loop msg gl_0)
      loop msg gl_0 = withTagM
        (pure (case msg.fieldMaskUnknownFields of { [] -> msg { fieldMaskPaths = growListToVector gl_0 }; _ -> msg { fieldMaskPaths = growListToVector gl_0, fieldMaskUnknownFields = reverse (msg.fieldMaskUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldString
            loop msg (snocGrowList gl_0 v)
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { fieldMaskUnknownFields = (uf : msg.fieldMaskUnknownFields)}) gl_0)

-- | Field descriptors for 'FieldMask', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
fieldMaskFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor FieldMask)
fieldMaskFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "paths"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelRepeated
        , fdGet = fieldMaskPaths
        , fdSet = \v m -> m { fieldMaskPaths = v }
        })
    ]

instance ProtoMessage FieldMask where
  protoMessageName _ = "google.protobuf.FieldMask"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultFieldMask
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = fieldMaskFieldDescriptors

instance IsMessage FieldMask

instance Aeson.ToJSON FieldMask where
  toJSON msg = jsonObject
      [ "paths" .=: msg.fieldMaskPaths

      ]

instance Aeson.FromJSON FieldMask where
  parseJSON = Aeson.withObject "FieldMask" $ \obj -> do
    fld_fieldMaskPaths <- parseFieldMaybe obj "paths"
    pure defaultFieldMask
      { fieldMaskPaths = maybe (fieldMaskPaths defaultFieldMask) id fld_fieldMaskPaths
      }

instance Hashable FieldMask where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.fieldMaskPaths

instance Proto.Extension.HasExtensions FieldMask where
  messageUnknownFields = fieldMaskUnknownFields
  setMessageUnknownFields !ufs msg = msg { fieldMaskUnknownFields = ufs }

instance Semigroup FieldMask where
  a <> b = FieldMask
    { fieldMaskPaths = a.fieldMaskPaths <> b.fieldMaskPaths
    , fieldMaskUnknownFields = a.fieldMaskUnknownFields <> b.fieldMaskUnknownFields
    }

instance Monoid FieldMask where
  mempty = defaultFieldMask