{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.WellKnownTypes.Struct where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word8, Word32, Word64)
import qualified Data.IntMap.Strict as IntMap
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Internal.Encode
import Proto.Internal.Decode
import Proto.Internal.GrowList (GrowList, emptyGrowList, snocGrowList, growListToVector)
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON, OneofVariantNullSemantics (..), parseOneofVariants)
import Data.Proxy (Proxy(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Decode.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x1c\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x73\x74\x72\x75\x63\x74\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x5b\x0a\x06\x53\x74\x72\x75\x63\x74\x12\x1b\x0a\x06\x66\x69\x65\x6c\x64\x73\x18\x01\x20\x03\x28\x0b\x32\x0b\x66\x69\x65\x6c\x64\x73\x45\x6e\x74\x72\x79\x1a\x34\x0a\x0b\x66\x69\x65\x6c\x64\x73\x45\x6e\x74\x72\x79\x12\x0b\x0a\x03\x6b\x65\x79\x18\x01\x20\x01\x28\x09\x12\x14\x0a\x05\x76\x61\x6c\x75\x65\x18\x02\x20\x01\x28\x0b\x32\x05\x56\x61\x6c\x75\x65\x3a\x02\x38\x01\x22\xab\x01\x0a\x05\x56\x61\x6c\x75\x65\x12\x1d\x0a\x0a\x6e\x75\x6c\x6c\x5f\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x0b\x32\x09\x4e\x75\x6c\x6c\x56\x61\x6c\x75\x65\x12\x14\x0a\x0c\x6e\x75\x6d\x62\x65\x72\x5f\x76\x61\x6c\x75\x65\x18\x02\x20\x01\x28\x01\x12\x14\x0a\x0c\x73\x74\x72\x69\x6e\x67\x5f\x76\x61\x6c\x75\x65\x18\x03\x20\x01\x28\x09\x12\x12\x0a\x0a\x62\x6f\x6f\x6c\x5f\x76\x61\x6c\x75\x65\x18\x04\x20\x01\x28\x08\x12\x1c\x0a\x0c\x73\x74\x72\x75\x63\x74\x5f\x76\x61\x6c\x75\x65\x18\x05\x20\x01\x28\x0b\x32\x06\x53\x74\x72\x75\x63\x74\x12\x1d\x0a\x0a\x6c\x69\x73\x74\x5f\x76\x61\x6c\x75\x65\x18\x06\x20\x01\x28\x0b\x32\x09\x4c\x69\x73\x74\x56\x61\x6c\x75\x65\x42\x06\x0a\x04\x6b\x69\x6e\x64\x22\x22\x0a\x09\x4c\x69\x73\x74\x56\x61\x6c\x75\x65\x12\x15\x0a\x06\x76\x61\x6c\x75\x65\x73\x18\x01\x20\x03\x28\x0b\x32\x05\x56\x61\x6c\x75\x65\x2a\x1b\x0a\x09\x4e\x75\x6c\x6c\x56\x61\x6c\x75\x65\x12\x0e\x0a\x0a\x4e\x55\x4c\x4c\x5f\x56\x41\x4c\x55\x45\x10\x00\x62\x06\x70\x72\x6f\x74\x6f\x33"


data Struct = Struct
  { structFields :: !(Map.Map Text Value)
  , structUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultStruct :: Struct
defaultStruct = Struct
  { structFields = Map.empty
  , structUnknownFields = []
  }

instance MessageEncode Struct where
  buildSized msg =
    Map.foldlWithKey' (\acc k v -> acc <> mapField 1 (fieldString 1 k) ((fieldMessage 2 . buildSized) v)) mempty msg.structFields
    <> encodeUnknownFieldsSized msg.structUnknownFields

instance MessageDecode Struct where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop defaultStruct
    where
      loop msg = withTagM
        (pure (case msg.structUnknownFields of { [] -> msg; _ -> msg { structUnknownFields = reverse (msg.structUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            bs' <- getLengthDelimited
            let decodeEntry = runDecoder (decodeMapEntry decodeFieldString decodeFieldMessage "" defaultValue) bs'
            case decodeEntry of
              Left _ -> loop msg
              Right (mk', mv') -> loop (msg { structFields = (Map.union msg.structFields (Map.singleton mk' mv'))})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { structUnknownFields = (uf : msg.structUnknownFields)}))

-- | Field descriptors for 'Struct', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
structFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor Struct)
structFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "fields"
        , fdNumber = 1
        , fdTypeDesc = ScalarType BytesField
        , fdLabel = LabelRepeated
        , fdGet = structFields
        , fdSet = \v m -> m { structFields = v }
        })
    ]

instance ProtoMessage Struct where
  protoMessageName _ = "google.protobuf.Struct"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultStruct
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = structFieldDescriptors

instance IsMessage Struct

instance Aeson.ToJSON Struct where
  toJSON msg = jsonObject
      [ "fields" .=: msg.structFields

      ]

instance Aeson.FromJSON Struct where
  parseJSON = Aeson.withObject "Struct" $ \obj -> do
    fld_structFields <- parseFieldMaybe obj "fields"
    pure defaultStruct
      { structFields = maybe (structFields defaultStruct) id fld_structFields
      }

instance Hashable Struct where
  hashWithSalt salt msg = Map.foldlWithKey' (\s k v -> s `hashWithSalt` k `hashWithSalt` v) (salt) msg.structFields

instance Proto.Extension.HasExtensions Struct where
  messageUnknownFields = structUnknownFields
  setMessageUnknownFields !ufs msg = msg { structUnknownFields = ufs }

instance Semigroup Struct where
  a <> b = Struct
    { structFields = a.structFields <> b.structFields
    , structUnknownFields = a.structUnknownFields <> b.structUnknownFields
    }

instance Monoid Struct where
  mempty = defaultStruct

data Value = Value
  { valueKind :: !(Maybe Value'Kind)
  , valueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data Value'Kind
  = Value'Kind'NullValue !NullValue
  | Value'Kind'NumberValue {-# UNPACK #-} !Double
  | Value'Kind'StringValue !Text
  | Value'Kind'BoolValue {-# UNPACK #-} !Bool
  | Value'Kind'StructValue !Struct
  | Value'Kind'ListValue !ListValue
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance Aeson.ToJSON Value'Kind where
  toJSON v0 = jsonObject (case v0 of
    Value'Kind'NullValue v -> ["nullValue" .=: v]
    Value'Kind'NumberValue v -> ["numberValue" .=: v]
    Value'Kind'StringValue v -> ["stringValue" .=: v]
    Value'Kind'BoolValue v -> ["boolValue" .=: v]
    Value'Kind'StructValue v -> ["structValue" .=: v]
    Value'Kind'ListValue v -> ["listValue" .=: v]
    )
instance Aeson.FromJSON Value'Kind where
  parseJSON = Aeson.withObject "Value'Kind" $ \obj -> do
    mr <- parseOneofVariants obj
      [ ("nullValue", OneofVariantNullIsUnset, (\v -> Value'Kind'NullValue <$> Aeson.parseJSON v))
      , ("numberValue", OneofVariantNullIsUnset, (\v -> Value'Kind'NumberValue <$> Aeson.parseJSON v))
      , ("stringValue", OneofVariantNullIsUnset, (\v -> Value'Kind'StringValue <$> Aeson.parseJSON v))
      , ("boolValue", OneofVariantNullIsUnset, (\v -> Value'Kind'BoolValue <$> Aeson.parseJSON v))
      , ("structValue", OneofVariantNullIsUnset, (\v -> Value'Kind'StructValue <$> Aeson.parseJSON v))
      , ("listValue", OneofVariantNullIsUnset, (\v -> Value'Kind'ListValue <$> Aeson.parseJSON v))
      ]
    case mr of
      Just v -> pure v
      Nothing -> fail "Expected one of: nullValue, numberValue, stringValue, boolValue, structValue, listValue"
instance Hashable Value'Kind where
  hashWithSalt salt (Value'Kind'NullValue v) = salt `hashWithSalt` (0 :: Int) `hashWithSalt` v
  hashWithSalt salt (Value'Kind'NumberValue v) = salt `hashWithSalt` (1 :: Int) `hashWithSalt` v
  hashWithSalt salt (Value'Kind'StringValue v) = salt `hashWithSalt` (2 :: Int) `hashWithSalt` v
  hashWithSalt salt (Value'Kind'BoolValue v) = salt `hashWithSalt` (3 :: Int) `hashWithSalt` v
  hashWithSalt salt (Value'Kind'StructValue v) = salt `hashWithSalt` (4 :: Int) `hashWithSalt` v
  hashWithSalt salt (Value'Kind'ListValue v) = salt `hashWithSalt` (5 :: Int) `hashWithSalt` v

defaultValue :: Value
defaultValue = Value
  { valueKind = Nothing
  , valueUnknownFields = []
  }

instance MessageEncode Value where
  buildSized msg =
    (case msg.valueKind of
      Nothing -> mempty
      Just (Value'Kind'NullValue v) -> archSubmessage 10 (buildSized v)
      Just (Value'Kind'NumberValue v) -> archDouble 17 v
      Just (Value'Kind'StringValue v) -> archString 26 v
      Just (Value'Kind'BoolValue v) -> archBool 32 v
      Just (Value'Kind'StructValue v) -> archSubmessage 42 (buildSized v)
      Just (Value'Kind'ListValue v) -> archSubmessage 50 (buildSized v))
    <> encodeUnknownFieldsSized msg.valueUnknownFields

instance MessageDecode Value where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultValue
    where
      stage_0 msg =
        inOrderStage1
          (0xa :: Data.Word.Word8)
          decodeFieldMessage
          (\v -> loop (msg { valueKind = (Just (Value'Kind'NullValue v))}))
          (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
          (inOrderStage1
            (0x11 :: Data.Word.Word8)
            decodeFieldDouble
            (\v -> loop (msg { valueKind = (Just (Value'Kind'NumberValue v))}))
            (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
            (inOrderStage1
              (0x1a :: Data.Word.Word8)
              decodeFieldString
              (\v -> loop (msg { valueKind = (Just (Value'Kind'StringValue v))}))
              (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
              (inOrderStage1
                (0x20 :: Data.Word.Word8)
                decodeFieldBool
                (\v -> loop (msg { valueKind = (Just (Value'Kind'BoolValue v))}))
                (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
                (inOrderStage1
                  (0x2a :: Data.Word.Word8)
                  decodeFieldMessage
                  (\v -> loop (msg { valueKind = (Just (Value'Kind'StructValue v))}))
                  (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
                  (inOrderStage1
                    (0x32 :: Data.Word.Word8)
                    decodeFieldMessage
                    (\v -> loop (msg { valueKind = (Just (Value'Kind'ListValue v))}))
                    (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
                    ((loop msg)))))))
      loop msg = withTagM
        (pure (case msg.valueUnknownFields of { [] -> msg; _ -> msg { valueUnknownFields = reverse (msg.valueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop (msg { valueKind = (Just (Value'Kind'NullValue v))})
          2 -> do
            v <- decodeFieldDouble
            loop (msg { valueKind = (Just (Value'Kind'NumberValue v))})
          3 -> do
            v <- decodeFieldString
            loop (msg { valueKind = (Just (Value'Kind'StringValue v))})
          4 -> do
            v <- decodeFieldBool
            loop (msg { valueKind = (Just (Value'Kind'BoolValue v))})
          5 -> do
            v <- decodeFieldMessage
            loop (msg { valueKind = (Just (Value'Kind'StructValue v))})
          6 -> do
            v <- decodeFieldMessage
            loop (msg { valueKind = (Just (Value'Kind'ListValue v))})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { valueUnknownFields = (uf : msg.valueUnknownFields)}))

-- | Field descriptors for 'Value', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
valueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor Value)
valueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "kind"
        , fdNumber = 1
        , fdTypeDesc = MessageType "kind"
        , fdLabel = LabelOptional
        , fdGet = valueKind
        , fdSet = \v m -> m { valueKind = v }
        })
    ]

instance ProtoMessage Value where
  protoMessageName _ = "google.protobuf.Value"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = valueFieldDescriptors

instance IsMessage Value

instance Aeson.ToJSON Value where
  toJSON msg = jsonObject $ mconcat
      [ (case msg.valueKind of
          Nothing -> []
          Just (Value'Kind'NullValue v) -> ["nullValue" .=: v]
          Just (Value'Kind'NumberValue v) -> ["numberValue" .=: v]
          Just (Value'Kind'StringValue v) -> ["stringValue" .=: v]
          Just (Value'Kind'BoolValue v) -> ["boolValue" .=: v]
          Just (Value'Kind'StructValue v) -> ["structValue" .=: v]
          Just (Value'Kind'ListValue v) -> ["listValue" .=: v]
      )

      ]

instance Aeson.FromJSON Value where
  parseJSON = Aeson.withObject "Value" $ \obj -> do
    fld_valueKind <- parseOneofVariants obj
      [ ("nullValue", OneofVariantNullIsUnset, (\v -> Value'Kind'NullValue <$> Aeson.parseJSON v))
      , ("numberValue", OneofVariantNullIsUnset, (\v -> Value'Kind'NumberValue <$> Aeson.parseJSON v))
      , ("stringValue", OneofVariantNullIsUnset, (\v -> Value'Kind'StringValue <$> Aeson.parseJSON v))
      , ("boolValue", OneofVariantNullIsUnset, (\v -> Value'Kind'BoolValue <$> Aeson.parseJSON v))
      , ("structValue", OneofVariantNullIsUnset, (\v -> Value'Kind'StructValue <$> Aeson.parseJSON v))
      , ("listValue", OneofVariantNullIsUnset, (\v -> Value'Kind'ListValue <$> Aeson.parseJSON v))
      ]
    pure defaultValue
      { valueKind = fld_valueKind
      }

instance Hashable Value where
  hashWithSalt salt msg = hashWithSalt (salt) msg.valueKind

instance Proto.Extension.HasExtensions Value where
  messageUnknownFields = valueUnknownFields
  setMessageUnknownFields !ufs msg = msg { valueUnknownFields = ufs }

instance Semigroup Value where
  a <> b = Value
    { valueKind = case b.valueKind of { Nothing -> a.valueKind; x -> x }
    , valueUnknownFields = a.valueUnknownFields <> b.valueUnknownFields
    }

instance Monoid Value where
  mempty = defaultValue

data NullValue
  = NullValue'NullValue
  deriving stock (Show, Eq, Ord, Prelude.Enum, Prelude.Bounded, Generic)
  deriving anyclass NFData

toProtoEnumNullValue :: NullValue -> Int
toProtoEnumNullValue NullValue'NullValue = 0

fromProtoEnumNullValue :: Int -> Maybe NullValue
fromProtoEnumNullValue 0 = Just NullValue'NullValue
fromProtoEnumNullValue _ = Nothing

instance MessageEncode NullValue where
  buildSized _ = mempty
instance MessageDecode NullValue where
  messageDecoder = pure (Prelude.toEnum 0)

instance Aeson.ToJSON NullValue where
  toJSON NullValue'NullValue = Aeson.String "NULL_VALUE"

instance Aeson.FromJSON NullValue where
  parseJSON = \case
    Aeson.String "NULL_VALUE" -> pure NullValue'NullValue
    Aeson.Number n -> pure (Prelude.toEnum (round n))
    _ -> fail "Invalid enum value for NullValue"

instance Hashable NullValue where
  hashWithSalt salt x = hashWithSalt salt (toProtoEnumNullValue x)

data ListValue = ListValue
  { listValueValues :: !(V.Vector Value)
  , listValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultListValue :: ListValue
defaultListValue = ListValue
  { listValueValues = V.empty
  , listValueUnknownFields = []
  }

instance MessageEncode ListValue where
  buildSized msg =
    V.foldl' (\acc v -> acc <> archSubmessage 10 (buildSized v)) mempty msg.listValueValues
    <> encodeUnknownFieldsSized msg.listValueUnknownFields

instance MessageDecode ListValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultListValue emptyGrowList
    where
      stage_0 msg gl_0 =
        inOrderStage1
          (0xa :: Data.Word.Word8)
          decodeFieldMessage
          (\v -> stage_0 msg (snocGrowList gl_0 v))
          (pure (case msg.listValueUnknownFields of { [] -> msg { listValueValues = growListToVector gl_0 }; _ -> msg { listValueValues = growListToVector gl_0, listValueUnknownFields = reverse (msg.listValueUnknownFields) } }))
          (loop msg gl_0)
      loop msg gl_0 = withTagM
        (pure (case msg.listValueUnknownFields of { [] -> msg { listValueValues = growListToVector gl_0 }; _ -> msg { listValueValues = growListToVector gl_0, listValueUnknownFields = reverse (msg.listValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldMessage
            loop msg (snocGrowList gl_0 v)
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { listValueUnknownFields = (uf : msg.listValueUnknownFields)}) gl_0)

-- | Field descriptors for 'ListValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
listValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor ListValue)
listValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "values"
        , fdNumber = 1
        , fdTypeDesc = MessageType "Value"
        , fdLabel = LabelRepeated
        , fdGet = listValueValues
        , fdSet = \v m -> m { listValueValues = v }
        })
    ]

instance ProtoMessage ListValue where
  protoMessageName _ = "google.protobuf.ListValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultListValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = listValueFieldDescriptors

instance IsMessage ListValue

instance Aeson.ToJSON ListValue where
  toJSON msg = jsonObject
      [ "values" .=: msg.listValueValues

      ]

instance Aeson.FromJSON ListValue where
  parseJSON = Aeson.withObject "ListValue" $ \obj -> do
    fld_listValueValues <- parseFieldMaybe obj "values"
    pure defaultListValue
      { listValueValues = maybe (listValueValues defaultListValue) id fld_listValueValues
      }

instance Hashable ListValue where
  hashWithSalt salt msg = V.foldl' hashWithSalt (salt) msg.listValueValues

instance Proto.Extension.HasExtensions ListValue where
  messageUnknownFields = listValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { listValueUnknownFields = ufs }

instance Semigroup ListValue where
  a <> b = ListValue
    { listValueValues = a.listValueValues <> b.listValueValues
    , listValueUnknownFields = a.listValueUnknownFields <> b.listValueUnknownFields
    }

instance Monoid ListValue where
  mempty = defaultListValue