{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
-- | Auto-generated protobuf types from package @google.protobuf@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Google.Protobuf.WellKnownTypes.Wrappers where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word8, Word32, Word64)
import qualified Data.IntMap.Strict as IntMap
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Internal.Encode
import Proto.Internal.Decode
import Proto.Internal.GrowList (GrowList, emptyGrowList, snocGrowList, growListToVector)
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON, OneofVariantNullSemantics (..), parseOneofVariants)
import Data.Proxy (Proxy(..))
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Decode.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x1e\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x77\x72\x61\x70\x70\x65\x72\x73\x2e\x70\x72\x6f\x74\x6f\x12\x0f\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x22\x1c\x0a\x0b\x44\x6f\x75\x62\x6c\x65\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x01\x22\x1b\x0a\x0a\x46\x6c\x6f\x61\x74\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x02\x22\x1b\x0a\x0a\x49\x6e\x74\x36\x34\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x03\x22\x1c\x0a\x0b\x55\x49\x6e\x74\x36\x34\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x04\x22\x1b\x0a\x0a\x49\x6e\x74\x33\x32\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x05\x22\x1c\x0a\x0b\x55\x49\x6e\x74\x33\x32\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x0d\x22\x1a\x0a\x09\x42\x6f\x6f\x6c\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x08\x22\x1c\x0a\x0b\x53\x74\x72\x69\x6e\x67\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x09\x22\x1b\x0a\x0a\x42\x79\x74\x65\x73\x56\x61\x6c\x75\x65\x12\x0d\x0a\x05\x76\x61\x6c\x75\x65\x18\x01\x20\x01\x28\x0c\x62\x06\x70\x72\x6f\x74\x6f\x33"


data DoubleValue = DoubleValue
  { doubleValueValue :: {-# UNPACK #-} !Double
  , doubleValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultDoubleValue :: DoubleValue
defaultDoubleValue = DoubleValue
  { doubleValueValue = 0
  , doubleValueUnknownFields = []
  }

instance MessageEncode DoubleValue where
  buildSized msg =
    (if msg.doubleValueValue == 0 then mempty else archDouble 9 msg.doubleValueValue)
    <> encodeUnknownFieldsSized msg.doubleValueUnknownFields

instance MessageDecode DoubleValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultDoubleValue
    where
      stage_0 msg =
        inOrderStage1
          (0x9 :: Data.Word.Word8)
          decodeFieldDouble
          (\v -> loop (msg { doubleValueValue = v}))
          (pure (case msg.doubleValueUnknownFields of { [] -> msg; _ -> msg { doubleValueUnknownFields = reverse (msg.doubleValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.doubleValueUnknownFields of { [] -> msg; _ -> msg { doubleValueUnknownFields = reverse (msg.doubleValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldDouble
            loop (msg { doubleValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { doubleValueUnknownFields = (uf : msg.doubleValueUnknownFields)}))

-- | Field descriptors for 'DoubleValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
doubleValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor DoubleValue)
doubleValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType DoubleField
        , fdLabel = LabelOptional
        , fdGet = doubleValueValue
        , fdSet = \v m -> m { doubleValueValue = v }
        })
    ]

instance ProtoMessage DoubleValue where
  protoMessageName _ = "google.protobuf.DoubleValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultDoubleValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = doubleValueFieldDescriptors

instance IsMessage DoubleValue

instance Aeson.ToJSON DoubleValue where
  toJSON msg = jsonObject
      [ "value" .=: msg.doubleValueValue

      ]

instance Aeson.FromJSON DoubleValue where
  parseJSON = Aeson.withObject "DoubleValue" $ \obj -> do
    fld_doubleValueValue <- parseFieldMaybe obj "value"
    pure defaultDoubleValue
      { doubleValueValue = maybe (doubleValueValue defaultDoubleValue) id fld_doubleValueValue
      }

instance Hashable DoubleValue where
  hashWithSalt salt msg = hashWithSalt (salt) msg.doubleValueValue

instance Proto.Extension.HasExtensions DoubleValue where
  messageUnknownFields = doubleValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { doubleValueUnknownFields = ufs }

instance Semigroup DoubleValue where
  a <> b = DoubleValue
    { doubleValueValue = if b.doubleValueValue == 0 then a.doubleValueValue else b.doubleValueValue
    , doubleValueUnknownFields = a.doubleValueUnknownFields <> b.doubleValueUnknownFields
    }

instance Monoid DoubleValue where
  mempty = defaultDoubleValue

data FloatValue = FloatValue
  { floatValueValue :: {-# UNPACK #-} !Float
  , floatValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultFloatValue :: FloatValue
defaultFloatValue = FloatValue
  { floatValueValue = 0
  , floatValueUnknownFields = []
  }

instance MessageEncode FloatValue where
  buildSized msg =
    (if msg.floatValueValue == 0 then mempty else archFloat 13 msg.floatValueValue)
    <> encodeUnknownFieldsSized msg.floatValueUnknownFields

instance MessageDecode FloatValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultFloatValue
    where
      stage_0 msg =
        inOrderStage1
          (0xd :: Data.Word.Word8)
          decodeFieldFloat
          (\v -> loop (msg { floatValueValue = v}))
          (pure (case msg.floatValueUnknownFields of { [] -> msg; _ -> msg { floatValueUnknownFields = reverse (msg.floatValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.floatValueUnknownFields of { [] -> msg; _ -> msg { floatValueUnknownFields = reverse (msg.floatValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldFloat
            loop (msg { floatValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { floatValueUnknownFields = (uf : msg.floatValueUnknownFields)}))

-- | Field descriptors for 'FloatValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
floatValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor FloatValue)
floatValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType FloatField
        , fdLabel = LabelOptional
        , fdGet = floatValueValue
        , fdSet = \v m -> m { floatValueValue = v }
        })
    ]

instance ProtoMessage FloatValue where
  protoMessageName _ = "google.protobuf.FloatValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultFloatValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = floatValueFieldDescriptors

instance IsMessage FloatValue

instance Aeson.ToJSON FloatValue where
  toJSON msg = jsonObject
      [ "value" .=: msg.floatValueValue

      ]

instance Aeson.FromJSON FloatValue where
  parseJSON = Aeson.withObject "FloatValue" $ \obj -> do
    fld_floatValueValue <- parseFieldMaybe obj "value"
    pure defaultFloatValue
      { floatValueValue = maybe (floatValueValue defaultFloatValue) id fld_floatValueValue
      }

instance Hashable FloatValue where
  hashWithSalt salt msg = hashWithSalt (salt) msg.floatValueValue

instance Proto.Extension.HasExtensions FloatValue where
  messageUnknownFields = floatValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { floatValueUnknownFields = ufs }

instance Semigroup FloatValue where
  a <> b = FloatValue
    { floatValueValue = if b.floatValueValue == 0 then a.floatValueValue else b.floatValueValue
    , floatValueUnknownFields = a.floatValueUnknownFields <> b.floatValueUnknownFields
    }

instance Monoid FloatValue where
  mempty = defaultFloatValue

data Int64Value = Int64Value
  { int64ValueValue :: {-# UNPACK #-} !Int64
  , int64ValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultInt64Value :: Int64Value
defaultInt64Value = Int64Value
  { int64ValueValue = 0
  , int64ValueUnknownFields = []
  }

instance MessageEncode Int64Value where
  buildSized msg =
    (if msg.int64ValueValue == 0 then mempty else archVarint 8 (fromIntegral msg.int64ValueValue))
    <> encodeUnknownFieldsSized msg.int64ValueUnknownFields

instance MessageDecode Int64Value where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultInt64Value
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          (fromIntegral <$> decodeFieldVarint)
          (\v -> loop (msg { int64ValueValue = v}))
          (pure (case msg.int64ValueUnknownFields of { [] -> msg; _ -> msg { int64ValueUnknownFields = reverse (msg.int64ValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.int64ValueUnknownFields of { [] -> msg; _ -> msg { int64ValueUnknownFields = reverse (msg.int64ValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (msg { int64ValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { int64ValueUnknownFields = (uf : msg.int64ValueUnknownFields)}))

-- | Field descriptors for 'Int64Value', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
int64ValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor Int64Value)
int64ValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int64Field
        , fdLabel = LabelOptional
        , fdGet = int64ValueValue
        , fdSet = \v m -> m { int64ValueValue = v }
        })
    ]

instance ProtoMessage Int64Value where
  protoMessageName _ = "google.protobuf.Int64Value"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultInt64Value
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = int64ValueFieldDescriptors

instance IsMessage Int64Value

instance Aeson.ToJSON Int64Value where
  toJSON msg = jsonObject
      [ "value" .=: msg.int64ValueValue

      ]

instance Aeson.FromJSON Int64Value where
  parseJSON = Aeson.withObject "Int64Value" $ \obj -> do
    fld_int64ValueValue <- parseFieldMaybe obj "value"
    pure defaultInt64Value
      { int64ValueValue = maybe (int64ValueValue defaultInt64Value) id fld_int64ValueValue
      }

instance Hashable Int64Value where
  hashWithSalt salt msg = hashWithSalt (salt) msg.int64ValueValue

instance Proto.Extension.HasExtensions Int64Value where
  messageUnknownFields = int64ValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { int64ValueUnknownFields = ufs }

instance Semigroup Int64Value where
  a <> b = Int64Value
    { int64ValueValue = if b.int64ValueValue == 0 then a.int64ValueValue else b.int64ValueValue
    , int64ValueUnknownFields = a.int64ValueUnknownFields <> b.int64ValueUnknownFields
    }

instance Monoid Int64Value where
  mempty = defaultInt64Value

data UInt64Value = UInt64Value
  { uInt64ValueValue :: {-# UNPACK #-} !Word64
  , uInt64ValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultUInt64Value :: UInt64Value
defaultUInt64Value = UInt64Value
  { uInt64ValueValue = 0
  , uInt64ValueUnknownFields = []
  }

instance MessageEncode UInt64Value where
  buildSized msg =
    (if msg.uInt64ValueValue == 0 then mempty else archVarint 8 msg.uInt64ValueValue)
    <> encodeUnknownFieldsSized msg.uInt64ValueUnknownFields

instance MessageDecode UInt64Value where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultUInt64Value
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          decodeFieldVarint
          (\v -> loop (msg { uInt64ValueValue = v}))
          (pure (case msg.uInt64ValueUnknownFields of { [] -> msg; _ -> msg { uInt64ValueUnknownFields = reverse (msg.uInt64ValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.uInt64ValueUnknownFields of { [] -> msg; _ -> msg { uInt64ValueUnknownFields = reverse (msg.uInt64ValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldVarint
            loop (msg { uInt64ValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { uInt64ValueUnknownFields = (uf : msg.uInt64ValueUnknownFields)}))

-- | Field descriptors for 'UInt64Value', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
uInt64ValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor UInt64Value)
uInt64ValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType UInt64Field
        , fdLabel = LabelOptional
        , fdGet = uInt64ValueValue
        , fdSet = \v m -> m { uInt64ValueValue = v }
        })
    ]

instance ProtoMessage UInt64Value where
  protoMessageName _ = "google.protobuf.UInt64Value"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultUInt64Value
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = uInt64ValueFieldDescriptors

instance IsMessage UInt64Value

instance Aeson.ToJSON UInt64Value where
  toJSON msg = jsonObject
      [ "value" .=: msg.uInt64ValueValue

      ]

instance Aeson.FromJSON UInt64Value where
  parseJSON = Aeson.withObject "UInt64Value" $ \obj -> do
    fld_uInt64ValueValue <- parseFieldMaybe obj "value"
    pure defaultUInt64Value
      { uInt64ValueValue = maybe (uInt64ValueValue defaultUInt64Value) id fld_uInt64ValueValue
      }

instance Hashable UInt64Value where
  hashWithSalt salt msg = hashWithSalt (salt) msg.uInt64ValueValue

instance Proto.Extension.HasExtensions UInt64Value where
  messageUnknownFields = uInt64ValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { uInt64ValueUnknownFields = ufs }

instance Semigroup UInt64Value where
  a <> b = UInt64Value
    { uInt64ValueValue = if b.uInt64ValueValue == 0 then a.uInt64ValueValue else b.uInt64ValueValue
    , uInt64ValueUnknownFields = a.uInt64ValueUnknownFields <> b.uInt64ValueUnknownFields
    }

instance Monoid UInt64Value where
  mempty = defaultUInt64Value

data Int32Value = Int32Value
  { int32ValueValue :: {-# UNPACK #-} !Int32
  , int32ValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultInt32Value :: Int32Value
defaultInt32Value = Int32Value
  { int32ValueValue = 0
  , int32ValueUnknownFields = []
  }

instance MessageEncode Int32Value where
  buildSized msg =
    (if msg.int32ValueValue == 0 then mempty else archVarint 8 (fromIntegral msg.int32ValueValue))
    <> encodeUnknownFieldsSized msg.int32ValueUnknownFields

instance MessageDecode Int32Value where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultInt32Value
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          (fromIntegral <$> decodeFieldVarint)
          (\v -> loop (msg { int32ValueValue = v}))
          (pure (case msg.int32ValueUnknownFields of { [] -> msg; _ -> msg { int32ValueUnknownFields = reverse (msg.int32ValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.int32ValueUnknownFields of { [] -> msg; _ -> msg { int32ValueUnknownFields = reverse (msg.int32ValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (msg { int32ValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { int32ValueUnknownFields = (uf : msg.int32ValueUnknownFields)}))

-- | Field descriptors for 'Int32Value', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
int32ValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor Int32Value)
int32ValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = int32ValueValue
        , fdSet = \v m -> m { int32ValueValue = v }
        })
    ]

instance ProtoMessage Int32Value where
  protoMessageName _ = "google.protobuf.Int32Value"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultInt32Value
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = int32ValueFieldDescriptors

instance IsMessage Int32Value

instance Aeson.ToJSON Int32Value where
  toJSON msg = jsonObject
      [ "value" .=: msg.int32ValueValue

      ]

instance Aeson.FromJSON Int32Value where
  parseJSON = Aeson.withObject "Int32Value" $ \obj -> do
    fld_int32ValueValue <- parseFieldMaybe obj "value"
    pure defaultInt32Value
      { int32ValueValue = maybe (int32ValueValue defaultInt32Value) id fld_int32ValueValue
      }

instance Hashable Int32Value where
  hashWithSalt salt msg = hashWithSalt (salt) msg.int32ValueValue

instance Proto.Extension.HasExtensions Int32Value where
  messageUnknownFields = int32ValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { int32ValueUnknownFields = ufs }

instance Semigroup Int32Value where
  a <> b = Int32Value
    { int32ValueValue = if b.int32ValueValue == 0 then a.int32ValueValue else b.int32ValueValue
    , int32ValueUnknownFields = a.int32ValueUnknownFields <> b.int32ValueUnknownFields
    }

instance Monoid Int32Value where
  mempty = defaultInt32Value

data UInt32Value = UInt32Value
  { uInt32ValueValue :: {-# UNPACK #-} !Word32
  , uInt32ValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultUInt32Value :: UInt32Value
defaultUInt32Value = UInt32Value
  { uInt32ValueValue = 0
  , uInt32ValueUnknownFields = []
  }

instance MessageEncode UInt32Value where
  buildSized msg =
    (if msg.uInt32ValueValue == 0 then mempty else archVarint 8 (fromIntegral msg.uInt32ValueValue))
    <> encodeUnknownFieldsSized msg.uInt32ValueUnknownFields

instance MessageDecode UInt32Value where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultUInt32Value
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          (fromIntegral <$> decodeFieldVarint)
          (\v -> loop (msg { uInt32ValueValue = v}))
          (pure (case msg.uInt32ValueUnknownFields of { [] -> msg; _ -> msg { uInt32ValueUnknownFields = reverse (msg.uInt32ValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.uInt32ValueUnknownFields of { [] -> msg; _ -> msg { uInt32ValueUnknownFields = reverse (msg.uInt32ValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (msg { uInt32ValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { uInt32ValueUnknownFields = (uf : msg.uInt32ValueUnknownFields)}))

-- | Field descriptors for 'UInt32Value', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
uInt32ValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor UInt32Value)
uInt32ValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType UInt32Field
        , fdLabel = LabelOptional
        , fdGet = uInt32ValueValue
        , fdSet = \v m -> m { uInt32ValueValue = v }
        })
    ]

instance ProtoMessage UInt32Value where
  protoMessageName _ = "google.protobuf.UInt32Value"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultUInt32Value
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = uInt32ValueFieldDescriptors

instance IsMessage UInt32Value

instance Aeson.ToJSON UInt32Value where
  toJSON msg = jsonObject
      [ "value" .=: msg.uInt32ValueValue

      ]

instance Aeson.FromJSON UInt32Value where
  parseJSON = Aeson.withObject "UInt32Value" $ \obj -> do
    fld_uInt32ValueValue <- parseFieldMaybe obj "value"
    pure defaultUInt32Value
      { uInt32ValueValue = maybe (uInt32ValueValue defaultUInt32Value) id fld_uInt32ValueValue
      }

instance Hashable UInt32Value where
  hashWithSalt salt msg = hashWithSalt (salt) msg.uInt32ValueValue

instance Proto.Extension.HasExtensions UInt32Value where
  messageUnknownFields = uInt32ValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { uInt32ValueUnknownFields = ufs }

instance Semigroup UInt32Value where
  a <> b = UInt32Value
    { uInt32ValueValue = if b.uInt32ValueValue == 0 then a.uInt32ValueValue else b.uInt32ValueValue
    , uInt32ValueUnknownFields = a.uInt32ValueUnknownFields <> b.uInt32ValueUnknownFields
    }

instance Monoid UInt32Value where
  mempty = defaultUInt32Value

data BoolValue = BoolValue
  { boolValueValue :: {-# UNPACK #-} !Bool
  , boolValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBoolValue :: BoolValue
defaultBoolValue = BoolValue
  { boolValueValue = False
  , boolValueUnknownFields = []
  }

instance MessageEncode BoolValue where
  buildSized msg =
    (if msg.boolValueValue == False then mempty else archBool 8 msg.boolValueValue)
    <> encodeUnknownFieldsSized msg.boolValueUnknownFields

instance MessageDecode BoolValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultBoolValue
    where
      stage_0 msg =
        inOrderStage1
          (0x8 :: Data.Word.Word8)
          decodeFieldBool
          (\v -> loop (msg { boolValueValue = v}))
          (pure (case msg.boolValueUnknownFields of { [] -> msg; _ -> msg { boolValueUnknownFields = reverse (msg.boolValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.boolValueUnknownFields of { [] -> msg; _ -> msg { boolValueUnknownFields = reverse (msg.boolValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldBool
            loop (msg { boolValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { boolValueUnknownFields = (uf : msg.boolValueUnknownFields)}))

-- | Field descriptors for 'BoolValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
boolValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor BoolValue)
boolValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType BoolField
        , fdLabel = LabelOptional
        , fdGet = boolValueValue
        , fdSet = \v m -> m { boolValueValue = v }
        })
    ]

instance ProtoMessage BoolValue where
  protoMessageName _ = "google.protobuf.BoolValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultBoolValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = boolValueFieldDescriptors

instance IsMessage BoolValue

instance Aeson.ToJSON BoolValue where
  toJSON msg = jsonObject
      [ "value" .=: msg.boolValueValue

      ]

instance Aeson.FromJSON BoolValue where
  parseJSON = Aeson.withObject "BoolValue" $ \obj -> do
    fld_boolValueValue <- parseFieldMaybe obj "value"
    pure defaultBoolValue
      { boolValueValue = maybe (boolValueValue defaultBoolValue) id fld_boolValueValue
      }

instance Hashable BoolValue where
  hashWithSalt salt msg = hashWithSalt (salt) msg.boolValueValue

instance Proto.Extension.HasExtensions BoolValue where
  messageUnknownFields = boolValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { boolValueUnknownFields = ufs }

instance Semigroup BoolValue where
  a <> b = BoolValue
    { boolValueValue = if b.boolValueValue == False then a.boolValueValue else b.boolValueValue
    , boolValueUnknownFields = a.boolValueUnknownFields <> b.boolValueUnknownFields
    }

instance Monoid BoolValue where
  mempty = defaultBoolValue

data StringValue = StringValue
  { stringValueValue :: !Text
  , stringValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultStringValue :: StringValue
defaultStringValue = StringValue
  { stringValueValue = ""
  , stringValueUnknownFields = []
  }

instance MessageEncode StringValue where
  buildSized msg =
    (if msg.stringValueValue == T.empty then mempty else archString 10 msg.stringValueValue)
    <> encodeUnknownFieldsSized msg.stringValueUnknownFields

instance MessageDecode StringValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultStringValue
    where
      stage_0 msg =
        inOrderStage1
          (0xa :: Data.Word.Word8)
          decodeFieldString
          (\v -> loop (msg { stringValueValue = v}))
          (pure (case msg.stringValueUnknownFields of { [] -> msg; _ -> msg { stringValueUnknownFields = reverse (msg.stringValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.stringValueUnknownFields of { [] -> msg; _ -> msg { stringValueUnknownFields = reverse (msg.stringValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldString
            loop (msg { stringValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { stringValueUnknownFields = (uf : msg.stringValueUnknownFields)}))

-- | Field descriptors for 'StringValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
stringValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor StringValue)
stringValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = stringValueValue
        , fdSet = \v m -> m { stringValueValue = v }
        })
    ]

instance ProtoMessage StringValue where
  protoMessageName _ = "google.protobuf.StringValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultStringValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = stringValueFieldDescriptors

instance IsMessage StringValue

instance Aeson.ToJSON StringValue where
  toJSON msg = jsonObject
      [ "value" .=: msg.stringValueValue

      ]

instance Aeson.FromJSON StringValue where
  parseJSON = Aeson.withObject "StringValue" $ \obj -> do
    fld_stringValueValue <- parseFieldMaybe obj "value"
    pure defaultStringValue
      { stringValueValue = maybe (stringValueValue defaultStringValue) id fld_stringValueValue
      }

instance Hashable StringValue where
  hashWithSalt salt msg = hashWithSalt (salt) msg.stringValueValue

instance Proto.Extension.HasExtensions StringValue where
  messageUnknownFields = stringValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { stringValueUnknownFields = ufs }

instance Semigroup StringValue where
  a <> b = StringValue
    { stringValueValue = if b.stringValueValue == "" then a.stringValueValue else b.stringValueValue
    , stringValueUnknownFields = a.stringValueUnknownFields <> b.stringValueUnknownFields
    }

instance Monoid StringValue where
  mempty = defaultStringValue

data BytesValue = BytesValue
  { bytesValueValue :: !ByteString
  , bytesValueUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultBytesValue :: BytesValue
defaultBytesValue = BytesValue
  { bytesValueValue = ""
  , bytesValueUnknownFields = []
  }

instance MessageEncode BytesValue where
  buildSized msg =
    (if BS.null msg.bytesValueValue then mempty else archBytes 10 msg.bytesValueValue)
    <> encodeUnknownFieldsSized msg.bytesValueUnknownFields

instance MessageDecode BytesValue where
  {-# INLINE messageDecoder #-}
  messageDecoder = stage_0 defaultBytesValue
    where
      stage_0 msg =
        inOrderStage1
          (0xa :: Data.Word.Word8)
          decodeFieldBytes
          (\v -> loop (msg { bytesValueValue = v}))
          (pure (case msg.bytesValueUnknownFields of { [] -> msg; _ -> msg { bytesValueUnknownFields = reverse (msg.bytesValueUnknownFields) } }))
          (loop msg)
      loop msg = withTagM
        (pure (case msg.bytesValueUnknownFields of { [] -> msg; _ -> msg { bytesValueUnknownFields = reverse (msg.bytesValueUnknownFields) } }))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldBytes
            loop (msg { bytesValueValue = v})
          _ -> do
            uf <- captureUnknownField fn (Prelude.toEnum wt)
            loop (msg { bytesValueUnknownFields = (uf : msg.bytesValueUnknownFields)}))

-- | Field descriptors for 'BytesValue', keyed by proto field number.
--
-- Top-level CAF: allocated lazily on first force, shared on every
-- subsequent 'protoFieldDescriptors' call (no per-call rebuild).
bytesValueFieldDescriptors :: IntMap.IntMap (SomeFieldDescriptor BytesValue)
bytesValueFieldDescriptors =
  IntMap.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "value"
        , fdNumber = 1
        , fdTypeDesc = ScalarType BytesField
        , fdLabel = LabelOptional
        , fdGet = bytesValueValue
        , fdSet = \v m -> m { bytesValueValue = v }
        })
    ]

instance ProtoMessage BytesValue where
  protoMessageName _ = "google.protobuf.BytesValue"
  protoPackageName _ = "google.protobuf"
  protoDefaultValue = defaultBytesValue
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = bytesValueFieldDescriptors

instance IsMessage BytesValue

instance Aeson.ToJSON BytesValue where
  toJSON msg = jsonObject
      [ bytesFieldToJSON "value" msg.bytesValueValue

      ]

instance Aeson.FromJSON BytesValue where
  parseJSON = Aeson.withObject "BytesValue" $ \obj -> do
    fld_bytesValueValue <- parseBytesFieldMaybe obj "value"
    pure defaultBytesValue
      { bytesValueValue = maybe (bytesValueValue defaultBytesValue) id fld_bytesValueValue
      }

instance Hashable BytesValue where
  hashWithSalt salt msg = hashWithSalt (salt) msg.bytesValueValue

instance Proto.Extension.HasExtensions BytesValue where
  messageUnknownFields = bytesValueUnknownFields
  setMessageUnknownFields !ufs msg = msg { bytesValueUnknownFields = ufs }

instance Semigroup BytesValue where
  a <> b = BytesValue
    { bytesValueValue = if b.bytesValueValue == "" then a.bytesValueValue else b.bytesValueValue
    , bytesValueUnknownFields = a.bytesValueUnknownFields <> b.bytesValueUnknownFields
    }

instance Monoid BytesValue where
  mempty = defaultBytesValue