{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE UndecidableInstances #-}

{- | Transport-agnostic service /implementations/.

This module is the shared vocabulary for implementing a Protobuf service
once and serving it over any transport that understands the
@'Protobuf' serv meth@ RPC tags — gRPC (@wireform-grpc@) and Connect
(@wireform-connect@) today.

== Defining a service implementation

Given service tags generated by @loadProtoServices@ (which also emits the
'ServiceMethods' instance), implement each method with 'method' and tie
the bundle together with 'service':

@
eliza :: MonadIO m => Service ElizaService m
eliza =
  service
    (  method \@Say       (\\req -> ...)
    :& method \@Introduce (\\req send -> ...)
    :& method \@Aggregate (\\recv -> ...)
    :& method \@Converse  (\\recv send -> ...)
    :& Done
    )
@

The registration is:

* __Order-insensitive__: 'service' reorders the handlers to match the
  @.proto@ declaration order ('ServiceMethods'); list them however you like.

* __Complete__: forgetting a method, listing one twice, or listing a
  method of a different service is a /compile-time/ error naming the
  offending method. A method you deliberately do not support is declared
  with 'methodUnimplemented', so the gap is visible in the source.

* __Streaming-kind-directed__: 'method' infers the handler shape from the
  RPC's 'RpcStreamingType'; there is one registration function, not four.
  The shapes are given by 'HandlerOf'.

* __Transport-neutral__: the same 'Service' value can be served over gRPC
  ('Network.GRPC.Server.Service.fromService' in @wireform-grpc@) and
  Connect (@connectHandlers@ in @wireform-connect@).

== Handler shapes

Per streaming kind ('HandlerOf'):

@
NonStreaming    : Input rpc -> m (Output rpc)
ClientStreaming : m (Maybe (Input rpc)) -> m (Output rpc)
ServerStreaming : Input rpc -> (Output rpc -> m ()) -> m ()
BiDiStreaming   : m (Maybe (Input rpc)) -> (Output rpc -> m ()) -> m ()
@

A @recv@ action returns 'Nothing' at end-of-stream; a @send@ continuation
may be called once per response message. Returning from the handler ends
the response stream — no explicit end-of-stream marker is needed.
-}
module Network.GRPC.Spec.Service (
  -- * Method list of a service
  ServiceMethods,

  -- * Handler shapes
  HandlerOf,

  -- * Single-method implementations
  MethodOf (..),
  method,
  methodUnimplemented,

  -- * Bundling
  Handlers (..),
  Service (..),
  service,

  -- * Completeness checking (exported for the benefit of type signatures)
  CompleteService (..),
  PluckMethod (..),

  -- * Adapter support
  unimplementedMessage,
) where

import Data.Kind (Constraint, Type)
import Data.Proxy (Proxy (..))
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding (decodeUtf8With)
import Data.Text.Encoding.Error (lenientDecode)
import GHC.TypeLits (ErrorMessage (..), Symbol, TypeError)

import Network.GRPC.Spec.RPC
import Network.GRPC.Spec.RPC.Protobuf (Protobuf)
import Network.GRPC.Spec.RPC.StreamType

{-------------------------------------------------------------------------------
  Method list of a service
-------------------------------------------------------------------------------}

{- | The methods of a Protobuf service, in @.proto@ declaration order.

Instances are generated by @loadProtoServices@
(@Network.GRPC.Protobuf.TH@ in @wireform-grpc@); for hand-written service
tags, define the instance manually:

@
type instance ServiceMethods MyService = '["methodOne", "methodTwo"]
@
-}
type family ServiceMethods (serv :: Type) :: [Symbol]

{-------------------------------------------------------------------------------
  Handler shapes
-------------------------------------------------------------------------------}

{- | The handler shape for an RPC, per streaming kind.

All actions live in the handler monad @m@; @recv@ returns 'Nothing' at
end-of-stream, and returning from the handler ends the response stream.
-}
type family HandlerOf (styp :: StreamingType) m (rpc :: Type) where
  HandlerOf 'NonStreaming m rpc =
    Input rpc -> m (Output rpc)
  HandlerOf 'ClientStreaming m rpc =
    m (Maybe (Input rpc)) -> m (Output rpc)
  HandlerOf 'ServerStreaming m rpc =
    Input rpc -> (Output rpc -> m ()) -> m ()
  HandlerOf 'BiDiStreaming m rpc =
    m (Maybe (Input rpc)) -> (Output rpc -> m ()) -> m ()

{-------------------------------------------------------------------------------
  Single-method implementations
-------------------------------------------------------------------------------}

{- | The implementation of one method of service @serv@, in monad @m@.

Construct with 'method' or 'methodUnimplemented' rather than the
constructors directly; transport adapters pattern-match on the
constructors.
-}
data MethodOf (serv :: Type) (meth :: Symbol) m where
  -- | An implemented method. The 'SStreamingType' singleton lets adapters
  -- refine 'HandlerOf' to the concrete handler shape.
  MethodImpl ::
       HasStreamingType (Protobuf serv meth)
    => SStreamingType (RpcStreamingType (Protobuf serv meth))
    -> HandlerOf (RpcStreamingType (Protobuf serv meth)) m (Protobuf serv meth)
    -> MethodOf serv meth m

  -- | A method this server deliberately does not implement. Transports
  -- respond with their native @unimplemented@ error
  -- (see 'unimplementedMessage').
  MethodUnimplemented ::
       HasStreamingType (Protobuf serv meth)
    => MethodOf serv meth m

{- | Implement one method of a service.

Apply to the RPC tag; the handler shape follows from the method's
streaming kind ('HandlerOf'):

@
method \@Say       :: (Input Say -> m (Output Say))              -> MethodOf Eliza "say" m
method \@Introduce :: (Input Introduce -> (Output Introduce -> m ()) -> m ()) -> ...
@
-}
method ::
     forall rpc serv meth m.
     ( rpc ~ Protobuf serv meth
     , HasStreamingType rpc
     )
  => HandlerOf (RpcStreamingType rpc) m rpc
  -> MethodOf serv meth m
method = MethodImpl (validStreamingType (Proxy @(RpcStreamingType rpc)))

{- | Declare that this server deliberately does not implement a method.

The transport responds with its native @unimplemented@ error. Using an
explicit marker (rather than simply omitting the method) keeps service
definitions complete: forgetting a method remains a compile error.
-}
methodUnimplemented ::
     forall rpc serv meth m.
     ( rpc ~ Protobuf serv meth
     , HasStreamingType rpc
     )
  => MethodOf serv meth m
methodUnimplemented = MethodUnimplemented

{-------------------------------------------------------------------------------
  Bundling
-------------------------------------------------------------------------------}

-- | A heterogeneous list of method implementations, in any order.
data Handlers (serv :: Type) (meths :: [Symbol]) m where
  Done :: Handlers serv '[] m
  (:&) ::
       MethodOf serv meth m
    -> Handlers serv meths m
    -> Handlers serv (meth ': meths) m

infixr 5 :&

{- | A complete implementation of service @serv@ in monad @m@: one
implementation per method, in canonical ('ServiceMethods') order.

Construct with 'service'.
-}
newtype Service (serv :: Type) m
  = Service (Handlers serv (ServiceMethods serv) m)

{- | Bundle per-method implementations ('method', 'methodUnimplemented')
into a complete 'Service'.

The handlers may be listed in any order; missing, duplicated, or foreign
methods are compile-time errors.
-}
service ::
     CompleteService serv (ServiceMethods serv) meths
  => Handlers serv meths m
  -> Service serv m
service = Service . canonicalize

{-------------------------------------------------------------------------------
  Completeness checking
-------------------------------------------------------------------------------}

{- | Proof that @have@ is a permutation of @want@.

@canonicalize@ reorders a 'Handlers' list into @want@ (canonical) order.
You should never need to write instances of this class; the three
instances below cover every case, with 'TypeError's for the failure modes.
-}
class CompleteService (serv :: Type) (want :: [Symbol]) (have :: [Symbol]) where
  canonicalize :: Handlers serv have m -> Handlers serv want m

instance CompleteService serv '[] '[] where
  canonicalize _ = Done

instance
  TypeError
    ( 'Text "Handler for a method that is not (or no longer) part of this service:"
        ':$$: 'Text "  " ':<>: 'ShowType (extra ': rest)
        ':$$: 'Text "Remove the extra (or duplicate) 'method' entries."
    )
  => CompleteService serv '[] (extra ': rest)
  where
  canonicalize = error "unreachable"

instance
  ( PluckMethod serv meth have rest
  , CompleteService serv want rest
  )
  => CompleteService serv (meth ': want) have
  where
  canonicalize hs =
    case pluck @serv @meth hs of
      (m, rest) -> m :& canonicalize rest

{- | Extract the handler for @meth@ from a 'Handlers' list, returning the
remainder. Type-level lookup by method name; drives 'CompleteService'.
-}
class PluckMethod (serv :: Type) (meth :: Symbol) (have :: [Symbol]) (rest :: [Symbol])
  | serv meth have -> rest
  where
  pluck :: Handlers serv have m -> (MethodOf serv meth m, Handlers serv rest m)

instance
  TypeError
    ( 'Text "Missing handler for method \"" ':<>: 'Text meth ':<>: 'Text "\" of "
        ':<>: 'ShowType serv ':<>: 'Text "."
        ':$$: 'Text "Add   method @<MethodTag> <handler>   to the 'service' list,"
        ':$$: 'Text "or declare it explicitly with   methodUnimplemented @<MethodTag>."
    )
  => PluckMethod serv meth '[] '[]
  where
  pluck = error "unreachable"

instance
  PluckMethod' (EqSymbol h meth) serv meth (h ': t) rest
  => PluckMethod serv meth (h ': t) rest
  where
  pluck = pluck' @(EqSymbol h meth)

-- | Helper for 'PluckMethod': dispatch on whether the head matches.
class PluckMethod' (match :: Bool) (serv :: Type) (meth :: Symbol) (have :: [Symbol]) (rest :: [Symbol])
  | match serv meth have -> rest
  where
  pluck' :: Handlers serv have m -> (MethodOf serv meth m, Handlers serv rest m)

instance PluckMethod' 'True serv meth (meth ': t) t where
  pluck' (m :& rest) = (m, rest)

instance
  PluckMethod serv meth t rest
  => PluckMethod' 'False serv meth (h ': t) (h ': rest)
  where
  pluck' (m :& rest) =
    case pluck @serv @meth rest of
      (m', rest') -> (m', m :& rest')

-- | Symbol equality as a closed type family (avoids the 'Data.Type.Equality.=='
-- overlapping-family subtleties).
type family EqSymbol (a :: Symbol) (b :: Symbol) :: Bool where
  EqSymbol a a = 'True
  EqSymbol a b = 'False

{-------------------------------------------------------------------------------
  Adapter support
-------------------------------------------------------------------------------}

{- | The error message transports should use when responding to a call of a
'methodUnimplemented' method: @\<service\>.\<Method\> is not implemented@.
-}
unimplementedMessage :: forall rpc. IsRPC rpc => Proxy rpc -> Text
unimplementedMessage p =
  Text.concat
    [ decodeUtf8With lenientDecode (rpcServiceName p)
    , "."
    , decodeUtf8With lenientDecode (rpcMethodName p)
    , " is not implemented"
    ]
